api_platform:
    title: Skill Card Project
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 20
        pagination_enabled: true
    use_symfony_listeners: true
    formats:
      jsonld: [ 'application/ld+json' ]
      json: [ 'application/json' ]