gesdinet_jwt_refresh_token:
  # Classe représentant le token de rafraîchissement (option déjà paramétrée, par défaut)
  refresh_token_class: App\Entity\RefreshToken
  # Pour que le token soit invalidé et supprimé après rafraîchissement, et qu'un nouveau soit fourni
  single_use: true
  # Cette option permet de stocker le token de rafraîchissement dans un cookie (sécurisé, comme pour le JWT) au lieu de le renvoyer dans le corps de la réponse.
  cookie:
    enabled: true
    #Afin que le token ne soit envoyé que sur les sous-routes /the_feed_api/public/api/token...
    path: /api/token

  logout_firewall: main